version: '3.5'
services:
  db:
    build: postgresql
    image: postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - clvr_ntwrk
  pgadmin:
    build: pgadmin
    image: pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - "db"
    networks:
      - clvr_ntwrk
  clevertec_task_rest:
    build: clevertec_task_rest
    image: clevertec_task_rest:1.0.0
    ports:
      - "80:8080"
    depends_on:
      - "pgadmin"
    restart: always
    networks:
      - clvr_ntwrk

networks:
  clvr_ntwrk:
    name: clvr_ntwrk
